---
title: "Practice Notebook"
output: html_notebook
---
## Loading libraries

```{r, echo=FALSE}
library(tidyverse) 
library(dslabs)
```

## Pivot Function

Converting the wide format table to tidy format table.

### Importing original data
Original data is in wide format

```{r}
path <- system.file("extdata", package="dslabs")
filename <- file.path(path, "fertility-two-countries-example.csv")
wide_data <- read_csv(filename)
```

```{r}
# snippet of wide data
wide_data %>% select(country, '1960':'1965')
```

```{r}
# move the values in the columns 1960 through 2015 into a single column
wide_data %>% pivot_longer(`1960`:`2015`)
```

```{r}
# another way to do this - only country isn't being pivoted
wide_data %>% pivot_longer(-country)
```

```{r}
# change the default column names
new_tidy_data <- wide_data %>% 
  pivot_longer(-country, names_to = "year", values_to = "fertility")
head(new_tidy_data)
```

```{r}
# in the new version (year is a character)
class(new_tidy_data$year)
```

```{r}
# use the names_transform argument to change the class of the year values to numeric
new_tidy_data <- wide_data %>% 
  pivot_longer(-country, names_to = "year", values_to = "fertility", 
               names_transform = list(year=as.numeric))
```

```{r}
# plot the data as before
new_tidy_data %>% ggplot(aes(year, fertility, color = country)) +
  geom_point()
```

## Separate table

```{r}
# import data
path <- system.file("extdata", package = "dslabs")
fname <-  "life-expectancy-and-fertility-two-countries-example.csv"
filename <- file.path(path, fname)
                     
raw_dat <- read_csv(filename)
select(raw_dat, 1:4)
```

First convert the wide table to long table

```{r}
dat <- raw_dat %>% pivot_longer(-country)
head(dat)
```

```{r}
dat %>% 
    separate(name, c("year", "name"), extra = "merge", convert = TRUE) %>%
    pivot_wider()
```

## Unite

```{r}
# using the data from the previous video
# if we had used this non-optimal approach to separate
dat %>% 
  separate(name, c("year", "name_1", "name_2"), 
           fill = "right", convert = TRUE)

# we could unite the second and third columns using unite()
dat %>% 
  separate(name, c("year", "name_1", "name_2"), 
           fill = "right", convert = TRUE) %>%
  unite(variable_name, name_1, name_2, sep="_")
  
# spread the columns
dat %>% 
  separate(name, c("year", "name_1", "name_2"), 
           fill = "right", convert = TRUE) %>%
  unite(name, name_1, name_2, sep="_") %>%
  spread(name, value) %>%
  rename(fertlity = fertility_NA)
```

